# Generated by Django 3.2.5 on 2021-07-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='albums', to='store.Artist'),
        ),
        migrations.AddField(
            model_name='booking',
            name='album',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.album'),
            preserve_default=False,
        ),
    ]
