# Generated by Django 3.2.5 on 2021-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_album_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(default=0, related_name='albums', to='store.Artist'),
        ),
    ]
