# Generated by Django 3.2.5 on 2021-07-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_album_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.contact'),
            preserve_default=False,
        ),
    ]
